In [3]:
import numpy as np
import math

# Array Creation

In [4]:
a = np.array([1,2,3])
print(a)
#print dimension
print(a.ndim)

[1 2 3]
1


In [5]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
#check types of item in array
b.dtype

dtype('int64')

In [7]:
#floats also accepted in array
c = np.array([1.2,3.4,5.2])
c.dtype.name

'float64'

In [8]:
#create filler arrays (know the shape of what you want)
d = np.zeros([2,3])
print(d)

e = np.ones([4,2])
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
#generate array of random float numbers
np.random.rand(2,2)

array([[0.13686675, 0.95224041],
       [0.28437448, 0.30283002]])

In [16]:
#generate array of random int numbers from 1 - 20 in size 2x2 array
np.random.randint(1,20,size=(2,2))

array([[18,  7],
       [17,  8]])

In [21]:
#create sequence of number array, first arg is start bound, second arg is end bound, third arg is the difference between 
#each consecutive numbers
f = np.arange(1,10,1)
print (f)
g = np.arange(1,10,2)
print (g)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [26]:
#create sequence of floats, third arg is total floats you want to generate
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# Array Operations

In [27]:
#Arithmetic Operations apply to each elements in array
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a + b
print(c)

d = a * b
print(d)

[5 7 9]
[ 4 10 18]


In [28]:
#Real World Problem-> Farenheit to Celcius Conversion

#create array of typical farenheit values
farenheit = np.array([0, -10, -5, 10, 15, 0])

#formula is (F-32) * 5/9 = C
celcius = (farenheit - 32) * 5/9
print(celcius)

[-17.77777778 -23.33333333 -20.55555556 -12.22222222  -9.44444444
 -17.77777778]


In [30]:
#boolean array
celcius > -20

array([ True, False, False,  True,  True,  True])

In [33]:
#other than elemental operations, numpy also do matrix operations
#create matrix
A = np.array([[1,2],[0,1]])
B = np.array([[0,1],[1,1]])

#for elemental manipulation, use *
print(A*B)

#for matrix manipulation, use @ or .
print(A@B)

[[0 2]
 [0 1]]
[[2 3]
 [1 1]]


In [43]:
C = np.array([[1,2],[3,4]])
print(C.sum())
print(C.max())
print(C.min())
print(C.mean())

10
4
1
2.5


In [45]:
array1 = np.arange(1,16,1).reshape(3,5)
print(array1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


# Slicing

In [46]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
#first arg is row
a[:2]
#means get first and second row

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
#second arg is column
a[:2, 1:3]
#means get first and second row but second and third column only

array([[2, 3],
       [6, 7]])

In [ ]:
#modifying sub array will modify the original array
